% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Apr-2026 23:13:31
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_3_invers_fungsi.mat');

K = 5;

N = 22;

a = 2;

alpha_lr = 0.003;

b = 2;

f_inv = saveVarsMat.f_inv; % <1x1 sym> unsupported class

f_x = saveVarsMat.f_x; % <1x1 sym> unsupported class

target_pendapatan = 504;

theta0 = 70;

volume_solve = saveVarsMat.volume_solve; % <1x1 sym> unsupported class

volume_subs = saveVarsMat.volume_subs; % <1x1 sym> unsupported class

x = saveVarsMat.x; % <1x1 sym> unsupported class

y = saveVarsMat.y; % <1x1 sym> unsupported class

clear saveVarsMat;
