% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Apr-2026 16:35:23
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_2_invers_citra.mat');

K = 5;

N = 22;

a = 2;

alpha_lr = 0.003;

b = saveVarsMat.b; % <1x1 matlab.graphics.chart.primitive.Bar> unsupported class

data_penjualan = [25; 30; 40; 38; 48; 53; 51];

nilai_median = 40;

rata_rata = 40.714285714285715;

standar_deviasi_populasi = 9.8519655140380955;

theta0 = 70;

clear saveVarsMat;
