% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Apr-2026 13:07:19
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_5_limit_kontinuan.mat');

K = 5;

N = 22;

a = 2;

alpha_lr = 0.003;

b = 2;

f_kanan = saveVarsMat.f_kanan; % <1x1 function_handle> unsupported class

f_kiri = saveVarsMat.f_kiri; % <1x1 function_handle> unsupported class

p = 10;

q = 0;

theta0 = 70;

clear saveVarsMat;
